### ISSUE TITLE
New tagged releases

### ISSUE THREAD

**Issue by JagCesar** [getsentry/fastlane-plugin-sentry#12]
Hey!

I just noticed you recently tagged both `v1.0.0` and `v1.0.1`. `v0.1.2` is still tagged as the latest release.

Just wanted to share that this pops up when using fast lane.

![screen shot 2017-03-02 at 15 33 37](https://cloud.githubusercontent.com/assets/923548/23511527/a190f1dc-ff5d-11e6-9f6d-8f02fa32001e.png)

So if these tags are purely experimental, get rid of them asap :P

Keep up the good work!

**Comment by HazAT** [comment]
Hey 
Thx I've noticed that like 15min ago ... please check again it should be tagged correctly now.

**Comment by JagCesar** [comment]
@HazAT Still pops up over here. Maybe fastlane caches this?

![screen shot 2017-03-02 at 15 41 02](https://cloud.githubusercontent.com/assets/923548/23511851/dfc1d5ba-ff5e-11e6-97ec-c704756845be.png)

**Comment by HazAT** [comment]
Can you make sure you run fastlane `>2`
and call `fastlane update_plugins` 
Because it looks like this over here:
<img width="579" alt="screen shot 2017-03-02 at 15 46 33" src="https://cloud.githubusercontent.com/assets/363802/23512029/84b1280a-ff5f-11e6-9f98-78cd7ec8841c.png">

**Comment by JagCesar** [comment]
Absolutely, that should fix the issue. But I wasn't sure if these are production ready releases since they aren't tagged as `Latest release`.

I assume they are production ready since you're asking me to update. Closing issue.
