### ISSUE TITLE
Option to fallback to `.sentryclirc` config

### ISSUE THREAD

**Issue by jakecraige** [getsentry/fastlane-plugin-sentry#15]
I have my project configured with a project `.sentryclirc` and computer specific for my auth token. I'd like to use this plugin to upload dSYMs as part of my fastlane process but currently it requires me to pass in those as options even though when it runs the command with `sentry-cli` it would work appropriately.

I understand having them as options is useful for people who don't configure the cli with the rc files, so I propose an option that allows it to skip the config validation and environment var overriding.

What do you think?

**Comment by HazAT** [comment]
Hey neat idea, after support for this is added in `sentry-cli` I will add it here.
https://github.com/getsentry/sentry-cli/issues/59
