### ISSUE TITLE
New app_identifier arguments cause unavoidable breaking change

### ISSUE THREAD

**Issue by wschurman** [getsentry/fastlane-plugin-sentry#22]
See comments on https://github.com/getsentry/fastlane-plugin-sentry/pull/19#pullrequestreview-39054097

These should either:
- Not have a default value (can't specify nil or empty string to override default value to get back previous behavior)
- Just be put in the version argument instead. Having a separate arg that is just concatenated on the version arg doesn't make sense as an API.

I'll submit a revert of d2d22d6fda4a88475889a53a836683b829e383ee and f218eddec2219f4e916b348d6f49638c4214bfdf unless anyone has objections.

**Comment by HazAT** [comment]
It is concatenated with a `-`, we don't want that people have to do it by themselves since is a thing which could easily be forgotten.
We can argue about the necessity of the default value but I don't want to remove the separate `app_identifier` parameter.

**Comment by wschurman** [comment]
I see. Just curious, is having the app identifier in the version number recommended? The CLI documentation doesn't mention it: https://docs.sentry.io/learn/cli/releases/#creating-releases

The reason this is a breaking change is that unless the user changes their fastlane setup, they would be opted-in to this new version numbering scheme (`app_identifier-version`) which I believe breaks the processing unless the client is also changed. Unfortunately, some clients can't be changed (i.e. they may already be released and sending data to just `version`), so the default behavior of the added args should match the behavior before the change.

I'll remove my PR and put up a new one that just removes the default value and verify that the behavior matches that of before the change. I would also say that we should do the same with the `dist` argument and make false the default value (see #24) so that users don't need to specify false in the command.

**Comment by HazAT** [comment]
Hey,
Sorry for the late reply, you are right the docs should be improved in this matter.
We've recently changed the whole release system which made this change necessary for our mobile clients.
Currently, it's only here https://docs.sentry.io/clients/react-native/sourcemaps/
I will merge your PR to remove the default value for now.

Thank you
