### ISSUE TITLE
Info.plist variables are not resolved properly

### ISSUE THREAD

**Issue by sgtsquiggs** [getsentry/fastlane-plugin-sentry#31]
When I upload dSYMs, I see them as related to `$(PRODUCT_NAME) ($(PRODUCT_BUNDLE_IDENTIFIER))` in Sentry. It does manage to get the correct version/build however.

**Comment by HazAT** [comment]
Hey, this is a error in sentry-cli.
I've created an issue there and will close this one.
https://github.com/getsentry/sentry-cli/issues/138

**Comment by HazAT** [comment]
Hey, can you try
https://github.com/getsentry/sentry-cli/releases/tag/1.24.1
this should fix the issue.
