### ISSUE TITLE
sentry_upload_dsym fails with TypeError

### ISSUE THREAD

**Issue by Swamii** [getsentry/fastlane-plugin-sentry#5]
Hello
After upgrading to the latest version (0.1.2) the dsym upload has stopped working for me. Here is the traceback:

```
TypeError: [!] no implicit conversion of nil into String
  /Users/x/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-plugin-sentry-0.1.2/lib/fastlane/plugin/sentry/actions/sentry_upload_dsym.rb:38:in `absolute_path'
  /Users/x/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-plugin-sentry-0.1.2/lib/fastlane/plugin/sentry/actions/sentry_upload_dsym.rb:38:in `block in run'
  /Users/x/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-plugin-sentry-0.1.2/lib/fastlane/plugin/sentry/actions/sentry_upload_dsym.rb:38:in `map'
  /Users/x/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-plugin-sentry-0.1.2/lib/fastlane/plugin/sentry/actions/sentry_upload_dsym.rb:38:in `run'
  ...
```

This seems to happen when `dsym_paths` is set, but `dsym_path` is not (it's nil). 

Changing line 38 in sentry_upload_dsym.rb from 
```ruby
dsym_paths = dsym_paths.map { |path| File.absolute_path(path) }
``` 
to 
```ruby
dsym_paths = dsym_paths.compact.map { |path| File.absolute_path(path) }
```
seems to fix it.

Tell me if you need any more information. Thanks for the product.

**Comment by joshdholtz** [comment]
@Swamii Thanks for the help! Not sure why there is a `nil` in there for you but I will make that change 😊

**Comment by jakecraige** [comment]
Seems like it's due to [this line](https://github.com/getsentry/fastlane-plugin-sentry/blob/master/lib/fastlane/plugin/sentry/actions/sentry_upload_dsym.rb#L37) using a param that is optional, so it appends a `nil` when it's not provided.

**Comment by Swamii** [comment]
Yes, that's what happened to me. Why that param is nil I don't know. This is my fastlane setup for dsym  upload:
```rb
lane :refresh_dsyms do |options|
  build = get_build_number()
  version = get_version_number()
  download_dsyms(build_number: build, version: version)
    
  sentry_upload_dsym(
    api_key: '..',
    org_slug: '..',
    project_slug: '..',
  )
```
