### ISSUE TITLE
Error installing upload_symbols_to_sentry

### ISSUE THREAD

**Issue by DClark5218** [getsentry/fastlane-plugin-sentry#7]
Hey guys,
when I try using the upload_symbols to sentry in fast lane I get prompted to upload to a new version of sentry by `fastlane add_plugin sentry`.

I add it, but I get this:
<img width="1022" alt="screen shot 2017-01-16 at 3 25 26 pm" src="https://cloud.githubusercontent.com/assets/4645553/21997984/54ec0298-dc00-11e6-8da8-2f04cc838f40.png">

Then after trying to install the gem through `sudo gem install json -v '1.8.6'` i get this:

<img width="698" alt="screen shot 2017-01-16 at 3 33 17 pm" src="https://cloud.githubusercontent.com/assets/4645553/21998161/224216ba-dc01-11e6-9bf5-a8ca2a641648.png">

But things still don't seem to work. Can anyone help me track down the issue fix, or point me in the right direction?

Thanks!

**Comment by HazAT** [comment]
Hey we recently pushed version `1.0.0` ... please consider updating since this version uses the `sentry-cli` in the brackground which can be installed with `brew install getsentry/tools/sentry-cli`
